# This is a basic workflow to help you get started with Actions

name: FTP Deploy

on: 
  push:
    branches: [ master ]
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: n5.nodehost.ca/home/uozymm/web/thomasg.dev/public_html
        username: uozymm
        password: ${{ secrets.FTP_PASSWORD }}
